sudo: false
language: python
python:
  - 2.7
install:
  - virtualenv .
  - mkdir -p buildout-cache/{eggs,downloads}
  - bin/pip install --no-deps -e git+https://github.com/plone/mockup#egg=mockup
  - bin/pip install --no-deps -e git+https://github.com/repodono/repodono.registry.git#egg=repodono.registry
  - bin/pip install zc.buildout
  - bin/buildout -Nc travis.cfg
  - sh bootstrap-js.sh
script:
  - bin/code-analysis
  - bin/coverage run --source=src bin/test
  - make test
after_success:
  - pip install -q coveralls==0.5
  - coveralls

notifications:
  email:
    - tommy.yu@auckland.ac.nz
