# -*- coding: utf-8 -*-
from repodono.storage.testing.layers import (
    RepodonoStorageLayer,

    REPODONO_STORAGE_FIXTURE,
    REPODONO_STORAGE_INTEGRATION_TESTING,
    REPODONO_STORAGE_FUNCTIONAL_TESTING,
    REPODONO_STORAGE_ACCEPTANCE_TESTING,

    RepodonoDummyStorageLayer,

    REPODONO_DUMMY_STORAGE_FIXTURE,
    REPODONO_DUMMY_STORAGE_INTEGRATION_TESTING,
    REPODONO_DUMMY_STORAGE_FUNCTIONAL_TESTING,
    REPODONO_DUMMY_STORAGE_ACCEPTANCE_TESTING,
)

__all__ = [
    'RepodonoStorageLayer',
    'REPODONO_STORAGE_FIXTURE',
    'REPODONO_STORAGE_INTEGRATION_TESTING',
    'REPODONO_STORAGE_FUNCTIONAL_TESTING',
    'REPODONO_STORAGE_ACCEPTANCE_TESTING',
    'RepodonoDummyStorageLayer',
    'REPODONO_DUMMY_STORAGE_FIXTURE',
    'REPODONO_DUMMY_STORAGE_INTEGRATION_TESTING',
    'REPODONO_DUMMY_STORAGE_FUNCTIONAL_TESTING',
    'REPODONO_DUMMY_STORAGE_ACCEPTANCE_TESTING',
]
